name: Android Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_android:
    defaults:
      run:
        working-directory: frontend
      
    name: EAS Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN_SECRET
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN_SECRET }}" ]; then
            echo "You must provide an EXPO_TOKEN_SECRET secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN_SECRET }}


      - name: Install dependencies
        run: npm install

      - name: Publish Android Build
        run: eas build -p android
